# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-03-01 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
